
services:
  app:
    build: .
    image: prujezdy-vlaku:latest
    container_name: prujezdy-vlaku
    ports:
      - "127.0.0.1:5000:8000"
    volumes:
      - ./db:/app/db
      - ./data_storage:/app/data_storage
    environment:
      - SECRET_KEY=změňte_mě_na_tajný_řetězec_min_32_znaků
      - TZ=Europe/Prague
    restart: unless-stopped
